version: "3"

services:
  db:
    build: db
    ports:
      - 1433

  node-srv:
    build: node-srv
    command: /bin/sh -c "/wait && npx prisma db push && npx ts-node app.ts"
    environment:
      - WAIT_HOSTS=db:1433
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "80:3000"
